/*----- PROTECTED REGION ID(CcdCameraChameleonClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        CcdCameraChameleonClass.cpp
//
// description : C++ source for the CcdCameraChameleonClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the CcdCameraChameleon once per process.
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <CcdCameraChameleonClass.h>

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass.cpp

//-------------------------------------------------------------------
/**
 *	Create CcdCameraChameleonClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_CcdCameraChameleon_class(const char *name) {
		return CcdCameraChameleon_ns::CcdCameraChameleonClass::init(name);
	}
}

namespace CcdCameraChameleon_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
CcdCameraChameleonClass *CcdCameraChameleonClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		CcdCameraChameleonClass::CcdCameraChameleonClass(string &s)
 * description : 	constructor for the CcdCameraChameleonClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
CcdCameraChameleonClass::CcdCameraChameleonClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering CcdCameraChameleonClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::constructor

	cout2 << "Leaving CcdCameraChameleonClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		CcdCameraChameleonClass::~CcdCameraChameleonClass()
 * description : 	destructor for the CcdCameraChameleonClass
 */
//--------------------------------------------------------
CcdCameraChameleonClass::~CcdCameraChameleonClass()
{
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		CcdCameraChameleonClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
CcdCameraChameleonClass *CcdCameraChameleonClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new CcdCameraChameleonClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		CcdCameraChameleonClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
CcdCameraChameleonClass *CcdCameraChameleonClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		playClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *playClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "playClass::execute(): arrived" << endl;
	((static_cast<CcdCameraChameleon *>(device))->play());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		pauseClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *pauseClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "pauseClass::execute(): arrived" << endl;
	((static_cast<CcdCameraChameleon *>(device))->pause());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		setExposureClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *setExposureClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "setExposureClass::execute(): arrived" << endl;
	((static_cast<CcdCameraChameleon *>(device))->set_exposure());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum CcdCameraChameleonClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum CcdCameraChameleonClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum CcdCameraChameleonClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "serialNumber";
	prop_desc = "";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("CcdCameraChameleon");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new CcdCameraChameleon(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		CcdCameraChameleon *dev = static_cast<CcdCameraChameleon *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::attribute_factory_before
	//	Attribute : frameRate
	frameRateAttrib	*framerate = new frameRateAttrib();
	Tango::UserDefaultAttrProp	framerate_prop;
	//	description	not set for frameRate
	framerate_prop.set_label("Frame Rate");
	framerate_prop.set_unit("fps");
	//	standard_unit	not set for frameRate
	//	display_unit	not set for frameRate
	//	format	not set for frameRate
	//	max_value	not set for frameRate
	//	min_value	not set for frameRate
	//	max_alarm	not set for frameRate
	//	min_alarm	not set for frameRate
	//	max_warning	not set for frameRate
	//	min_warning	not set for frameRate
	//	delta_t	not set for frameRate
	//	delta_val	not set for frameRate
	
	framerate->set_default_properties(framerate_prop);
	//	Not Polled
	framerate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(framerate);

	//	Attribute : brightness
	brightnessAttrib	*brightness = new brightnessAttrib();
	Tango::UserDefaultAttrProp	brightness_prop;
	//	description	not set for brightness
	brightness_prop.set_label("Brightness");
	//	unit	not set for brightness
	//	standard_unit	not set for brightness
	//	display_unit	not set for brightness
	//	format	not set for brightness
	//	max_value	not set for brightness
	//	min_value	not set for brightness
	//	max_alarm	not set for brightness
	//	min_alarm	not set for brightness
	//	max_warning	not set for brightness
	//	min_warning	not set for brightness
	//	delta_t	not set for brightness
	//	delta_val	not set for brightness
	
	brightness->set_default_properties(brightness_prop);
	//	Not Polled
	brightness->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(brightness);

	//	Attribute : exposure
	exposureAttrib	*exposure = new exposureAttrib();
	Tango::UserDefaultAttrProp	exposure_prop;
	//	description	not set for exposure
	exposure_prop.set_label("Exposure");
	exposure_prop.set_unit("EV");
	//	standard_unit	not set for exposure
	//	display_unit	not set for exposure
	//	format	not set for exposure
	//	max_value	not set for exposure
	//	min_value	not set for exposure
	//	max_alarm	not set for exposure
	//	min_alarm	not set for exposure
	//	max_warning	not set for exposure
	//	min_warning	not set for exposure
	//	delta_t	not set for exposure
	//	delta_val	not set for exposure
	
	exposure->set_default_properties(exposure_prop);
	//	Not Polled
	exposure->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(exposure);

	//	Attribute : gamma
	gammaAttrib	*gamma = new gammaAttrib();
	Tango::UserDefaultAttrProp	gamma_prop;
	//	description	not set for gamma
	gamma_prop.set_label("Gamma");
	//	unit	not set for gamma
	//	standard_unit	not set for gamma
	//	display_unit	not set for gamma
	//	format	not set for gamma
	//	max_value	not set for gamma
	//	min_value	not set for gamma
	//	max_alarm	not set for gamma
	//	min_alarm	not set for gamma
	//	max_warning	not set for gamma
	//	min_warning	not set for gamma
	//	delta_t	not set for gamma
	//	delta_val	not set for gamma
	
	gamma->set_default_properties(gamma_prop);
	//	Not Polled
	gamma->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gamma);

	//	Attribute : shutter
	shutterAttrib	*shutter = new shutterAttrib();
	Tango::UserDefaultAttrProp	shutter_prop;
	//	description	not set for shutter
	shutter_prop.set_label("Shutter");
	shutter_prop.set_unit("ms");
	//	standard_unit	not set for shutter
	//	display_unit	not set for shutter
	//	format	not set for shutter
	//	max_value	not set for shutter
	//	min_value	not set for shutter
	//	max_alarm	not set for shutter
	//	min_alarm	not set for shutter
	//	max_warning	not set for shutter
	//	min_warning	not set for shutter
	//	delta_t	not set for shutter
	//	delta_val	not set for shutter
	
	shutter->set_default_properties(shutter_prop);
	//	Not Polled
	shutter->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(shutter);

	//	Attribute : gain
	gainAttrib	*gain = new gainAttrib();
	Tango::UserDefaultAttrProp	gain_prop;
	//	description	not set for gain
	gain_prop.set_label("Gain");
	gain_prop.set_unit("dB");
	//	standard_unit	not set for gain
	//	display_unit	not set for gain
	//	format	not set for gain
	//	max_value	not set for gain
	//	min_value	not set for gain
	//	max_alarm	not set for gain
	//	min_alarm	not set for gain
	//	max_warning	not set for gain
	//	min_warning	not set for gain
	//	delta_t	not set for gain
	//	delta_val	not set for gain
	
	gain->set_default_properties(gain_prop);
	//	Not Polled
	gain->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gain);

	//	Attribute : x
	xAttrib	*x = new xAttrib();
	Tango::UserDefaultAttrProp	x_prop;
	//	description	not set for x
	//	label	not set for x
	//	unit	not set for x
	//	standard_unit	not set for x
	//	display_unit	not set for x
	//	format	not set for x
	//	max_value	not set for x
	//	min_value	not set for x
	//	max_alarm	not set for x
	//	min_alarm	not set for x
	//	max_warning	not set for x
	//	min_warning	not set for x
	//	delta_t	not set for x
	//	delta_val	not set for x
	
	x->set_default_properties(x_prop);
	//	Not Polled
	x->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(x);

	//	Attribute : y
	yAttrib	*y = new yAttrib();
	Tango::UserDefaultAttrProp	y_prop;
	//	description	not set for y
	//	label	not set for y
	//	unit	not set for y
	//	standard_unit	not set for y
	//	display_unit	not set for y
	//	format	not set for y
	//	max_value	not set for y
	//	min_value	not set for y
	//	max_alarm	not set for y
	//	min_alarm	not set for y
	//	max_warning	not set for y
	//	min_warning	not set for y
	//	delta_t	not set for y
	//	delta_val	not set for y
	
	y->set_default_properties(y_prop);
	//	Not Polled
	y->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(y);

	//	Attribute : a
	aAttrib	*a = new aAttrib();
	Tango::UserDefaultAttrProp	a_prop;
	//	description	not set for a
	//	label	not set for a
	//	unit	not set for a
	//	standard_unit	not set for a
	//	display_unit	not set for a
	//	format	not set for a
	//	max_value	not set for a
	//	min_value	not set for a
	//	max_alarm	not set for a
	//	min_alarm	not set for a
	//	max_warning	not set for a
	//	min_warning	not set for a
	//	delta_t	not set for a
	//	delta_val	not set for a
	
	a->set_default_properties(a_prop);
	//	Not Polled
	a->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(a);

	//	Attribute : b
	bAttrib	*b = new bAttrib();
	Tango::UserDefaultAttrProp	b_prop;
	//	description	not set for b
	//	label	not set for b
	//	unit	not set for b
	//	standard_unit	not set for b
	//	display_unit	not set for b
	//	format	not set for b
	//	max_value	not set for b
	//	min_value	not set for b
	//	max_alarm	not set for b
	//	min_alarm	not set for b
	//	max_warning	not set for b
	//	min_warning	not set for b
	//	delta_t	not set for b
	//	delta_val	not set for b
	
	b->set_default_properties(b_prop);
	//	Not Polled
	b->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(b);

	//	Attribute : frameRateAuto
	frameRateAutoAttrib	*framerateauto = new frameRateAutoAttrib();
	Tango::UserDefaultAttrProp	framerateauto_prop;
	//	description	not set for frameRateAuto
	//	label	not set for frameRateAuto
	//	unit	not set for frameRateAuto
	//	standard_unit	not set for frameRateAuto
	//	display_unit	not set for frameRateAuto
	//	format	not set for frameRateAuto
	//	max_value	not set for frameRateAuto
	//	min_value	not set for frameRateAuto
	//	max_alarm	not set for frameRateAuto
	//	min_alarm	not set for frameRateAuto
	//	max_warning	not set for frameRateAuto
	//	min_warning	not set for frameRateAuto
	//	delta_t	not set for frameRateAuto
	//	delta_val	not set for frameRateAuto
	
	framerateauto->set_default_properties(framerateauto_prop);
	//	Not Polled
	framerateauto->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(framerateauto);

	//	Attribute : frameRateOnOff
	frameRateOnOffAttrib	*framerateonoff = new frameRateOnOffAttrib();
	Tango::UserDefaultAttrProp	framerateonoff_prop;
	//	description	not set for frameRateOnOff
	//	label	not set for frameRateOnOff
	//	unit	not set for frameRateOnOff
	//	standard_unit	not set for frameRateOnOff
	//	display_unit	not set for frameRateOnOff
	//	format	not set for frameRateOnOff
	//	max_value	not set for frameRateOnOff
	//	min_value	not set for frameRateOnOff
	//	max_alarm	not set for frameRateOnOff
	//	min_alarm	not set for frameRateOnOff
	//	max_warning	not set for frameRateOnOff
	//	min_warning	not set for frameRateOnOff
	//	delta_t	not set for frameRateOnOff
	//	delta_val	not set for frameRateOnOff
	
	framerateonoff->set_default_properties(framerateonoff_prop);
	//	Not Polled
	framerateonoff->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(framerateonoff);

	//	Attribute : exposureAuto
	exposureAutoAttrib	*exposureauto = new exposureAutoAttrib();
	Tango::UserDefaultAttrProp	exposureauto_prop;
	//	description	not set for exposureAuto
	//	label	not set for exposureAuto
	//	unit	not set for exposureAuto
	//	standard_unit	not set for exposureAuto
	//	display_unit	not set for exposureAuto
	//	format	not set for exposureAuto
	//	max_value	not set for exposureAuto
	//	min_value	not set for exposureAuto
	//	max_alarm	not set for exposureAuto
	//	min_alarm	not set for exposureAuto
	//	max_warning	not set for exposureAuto
	//	min_warning	not set for exposureAuto
	//	delta_t	not set for exposureAuto
	//	delta_val	not set for exposureAuto
	
	exposureauto->set_default_properties(exposureauto_prop);
	//	Not Polled
	exposureauto->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(exposureauto);

	//	Attribute : exposureOnOff
	exposureOnOffAttrib	*exposureonoff = new exposureOnOffAttrib();
	Tango::UserDefaultAttrProp	exposureonoff_prop;
	//	description	not set for exposureOnOff
	//	label	not set for exposureOnOff
	//	unit	not set for exposureOnOff
	//	standard_unit	not set for exposureOnOff
	//	display_unit	not set for exposureOnOff
	//	format	not set for exposureOnOff
	//	max_value	not set for exposureOnOff
	//	min_value	not set for exposureOnOff
	//	max_alarm	not set for exposureOnOff
	//	min_alarm	not set for exposureOnOff
	//	max_warning	not set for exposureOnOff
	//	min_warning	not set for exposureOnOff
	//	delta_t	not set for exposureOnOff
	//	delta_val	not set for exposureOnOff
	
	exposureonoff->set_default_properties(exposureonoff_prop);
	//	Not Polled
	exposureonoff->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(exposureonoff);

	//	Attribute : exposureOnePush
	exposureOnePushAttrib	*exposureonepush = new exposureOnePushAttrib();
	Tango::UserDefaultAttrProp	exposureonepush_prop;
	//	description	not set for exposureOnePush
	//	label	not set for exposureOnePush
	//	unit	not set for exposureOnePush
	//	standard_unit	not set for exposureOnePush
	//	display_unit	not set for exposureOnePush
	//	format	not set for exposureOnePush
	//	max_value	not set for exposureOnePush
	//	min_value	not set for exposureOnePush
	//	max_alarm	not set for exposureOnePush
	//	min_alarm	not set for exposureOnePush
	//	max_warning	not set for exposureOnePush
	//	min_warning	not set for exposureOnePush
	//	delta_t	not set for exposureOnePush
	//	delta_val	not set for exposureOnePush
	
	exposureonepush->set_default_properties(exposureonepush_prop);
	//	Not Polled
	exposureonepush->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(exposureonepush);

	//	Attribute : gammaOnOff
	gammaOnOffAttrib	*gammaonoff = new gammaOnOffAttrib();
	Tango::UserDefaultAttrProp	gammaonoff_prop;
	//	description	not set for gammaOnOff
	//	label	not set for gammaOnOff
	//	unit	not set for gammaOnOff
	//	standard_unit	not set for gammaOnOff
	//	display_unit	not set for gammaOnOff
	//	format	not set for gammaOnOff
	//	max_value	not set for gammaOnOff
	//	min_value	not set for gammaOnOff
	//	max_alarm	not set for gammaOnOff
	//	min_alarm	not set for gammaOnOff
	//	max_warning	not set for gammaOnOff
	//	min_warning	not set for gammaOnOff
	//	delta_t	not set for gammaOnOff
	//	delta_val	not set for gammaOnOff
	
	gammaonoff->set_default_properties(gammaonoff_prop);
	//	Not Polled
	gammaonoff->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gammaonoff);

	//	Attribute : gainAuto
	gainAutoAttrib	*gainauto = new gainAutoAttrib();
	Tango::UserDefaultAttrProp	gainauto_prop;
	//	description	not set for gainAuto
	//	label	not set for gainAuto
	//	unit	not set for gainAuto
	//	standard_unit	not set for gainAuto
	//	display_unit	not set for gainAuto
	//	format	not set for gainAuto
	//	max_value	not set for gainAuto
	//	min_value	not set for gainAuto
	//	max_alarm	not set for gainAuto
	//	min_alarm	not set for gainAuto
	//	max_warning	not set for gainAuto
	//	min_warning	not set for gainAuto
	//	delta_t	not set for gainAuto
	//	delta_val	not set for gainAuto
	
	gainauto->set_default_properties(gainauto_prop);
	//	Not Polled
	gainauto->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gainauto);

	//	Attribute : gainOnePush
	gainOnePushAttrib	*gainonepush = new gainOnePushAttrib();
	Tango::UserDefaultAttrProp	gainonepush_prop;
	//	description	not set for gainOnePush
	//	label	not set for gainOnePush
	//	unit	not set for gainOnePush
	//	standard_unit	not set for gainOnePush
	//	display_unit	not set for gainOnePush
	//	format	not set for gainOnePush
	//	max_value	not set for gainOnePush
	//	min_value	not set for gainOnePush
	//	max_alarm	not set for gainOnePush
	//	min_alarm	not set for gainOnePush
	//	max_warning	not set for gainOnePush
	//	min_warning	not set for gainOnePush
	//	delta_t	not set for gainOnePush
	//	delta_val	not set for gainOnePush
	
	gainonepush->set_default_properties(gainonepush_prop);
	//	Not Polled
	gainonepush->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gainonepush);

	//	Attribute : shutterAuto
	shutterAutoAttrib	*shutterauto = new shutterAutoAttrib();
	Tango::UserDefaultAttrProp	shutterauto_prop;
	//	description	not set for shutterAuto
	//	label	not set for shutterAuto
	//	unit	not set for shutterAuto
	//	standard_unit	not set for shutterAuto
	//	display_unit	not set for shutterAuto
	//	format	not set for shutterAuto
	//	max_value	not set for shutterAuto
	//	min_value	not set for shutterAuto
	//	max_alarm	not set for shutterAuto
	//	min_alarm	not set for shutterAuto
	//	max_warning	not set for shutterAuto
	//	min_warning	not set for shutterAuto
	//	delta_t	not set for shutterAuto
	//	delta_val	not set for shutterAuto
	
	shutterauto->set_default_properties(shutterauto_prop);
	//	Not Polled
	shutterauto->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(shutterauto);

	//	Attribute : shutterOnePush
	shutterOnePushAttrib	*shutteronepush = new shutterOnePushAttrib();
	Tango::UserDefaultAttrProp	shutteronepush_prop;
	//	description	not set for shutterOnePush
	//	label	not set for shutterOnePush
	//	unit	not set for shutterOnePush
	//	standard_unit	not set for shutterOnePush
	//	display_unit	not set for shutterOnePush
	//	format	not set for shutterOnePush
	//	max_value	not set for shutterOnePush
	//	min_value	not set for shutterOnePush
	//	max_alarm	not set for shutterOnePush
	//	min_alarm	not set for shutterOnePush
	//	max_warning	not set for shutterOnePush
	//	min_warning	not set for shutterOnePush
	//	delta_t	not set for shutterOnePush
	//	delta_val	not set for shutterOnePush
	
	shutteronepush->set_default_properties(shutteronepush_prop);
	//	Not Polled
	shutteronepush->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(shutteronepush);

	//	Attribute : temperature
	temperatureAttrib	*temperature = new temperatureAttrib();
	Tango::UserDefaultAttrProp	temperature_prop;
	//	description	not set for temperature
	//	label	not set for temperature
	//	unit	not set for temperature
	//	standard_unit	not set for temperature
	//	display_unit	not set for temperature
	//	format	not set for temperature
	//	max_value	not set for temperature
	//	min_value	not set for temperature
	//	max_alarm	not set for temperature
	//	min_alarm	not set for temperature
	//	max_warning	not set for temperature
	//	min_warning	not set for temperature
	//	delta_t	not set for temperature
	//	delta_val	not set for temperature
	
	temperature->set_default_properties(temperature_prop);
	//	Not Polled
	temperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(temperature);

	//	Attribute : imageWidth
	imageWidthAttrib	*imagewidth = new imageWidthAttrib();
	Tango::UserDefaultAttrProp	imagewidth_prop;
	//	description	not set for imageWidth
	//	label	not set for imageWidth
	//	unit	not set for imageWidth
	//	standard_unit	not set for imageWidth
	//	display_unit	not set for imageWidth
	//	format	not set for imageWidth
	//	max_value	not set for imageWidth
	//	min_value	not set for imageWidth
	//	max_alarm	not set for imageWidth
	//	min_alarm	not set for imageWidth
	//	max_warning	not set for imageWidth
	//	min_warning	not set for imageWidth
	//	delta_t	not set for imageWidth
	//	delta_val	not set for imageWidth
	
	imagewidth->set_default_properties(imagewidth_prop);
	//	Not Polled
	imagewidth->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(imagewidth);

	//	Attribute : imageHeight
	imageHeightAttrib	*imageheight = new imageHeightAttrib();
	Tango::UserDefaultAttrProp	imageheight_prop;
	//	description	not set for imageHeight
	//	label	not set for imageHeight
	//	unit	not set for imageHeight
	//	standard_unit	not set for imageHeight
	//	display_unit	not set for imageHeight
	//	format	not set for imageHeight
	//	max_value	not set for imageHeight
	//	min_value	not set for imageHeight
	//	max_alarm	not set for imageHeight
	//	min_alarm	not set for imageHeight
	//	max_warning	not set for imageHeight
	//	min_warning	not set for imageHeight
	//	delta_t	not set for imageHeight
	//	delta_val	not set for imageHeight
	
	imageheight->set_default_properties(imageheight_prop);
	//	Not Polled
	imageheight->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(imageheight);

	//	Attribute : quality
	qualityAttrib	*quality = new qualityAttrib();
	Tango::UserDefaultAttrProp	quality_prop;
	//	description	not set for quality
	//	label	not set for quality
	//	unit	not set for quality
	//	standard_unit	not set for quality
	//	display_unit	not set for quality
	//	format	not set for quality
	//	max_value	not set for quality
	//	min_value	not set for quality
	//	max_alarm	not set for quality
	//	min_alarm	not set for quality
	//	max_warning	not set for quality
	//	min_warning	not set for quality
	//	delta_t	not set for quality
	//	delta_val	not set for quality
	
	quality->set_default_properties(quality_prop);
	//	Not Polled
	quality->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(quality);

	//	Attribute : phi
	phiAttrib	*phi = new phiAttrib();
	Tango::UserDefaultAttrProp	phi_prop;
	//	description	not set for phi
	//	label	not set for phi
	//	unit	not set for phi
	//	standard_unit	not set for phi
	//	display_unit	not set for phi
	//	format	not set for phi
	//	max_value	not set for phi
	//	min_value	not set for phi
	//	max_alarm	not set for phi
	//	min_alarm	not set for phi
	//	max_warning	not set for phi
	//	min_warning	not set for phi
	//	delta_t	not set for phi
	//	delta_val	not set for phi
	
	phi->set_default_properties(phi_prop);
	//	Not Polled
	phi->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(phi);

	//	Attribute : scale
	scaleAttrib	*scale = new scaleAttrib();
	Tango::UserDefaultAttrProp	scale_prop;
	//	description	not set for scale
	//	label	not set for scale
	//	unit	not set for scale
	//	standard_unit	not set for scale
	//	display_unit	not set for scale
	//	format	not set for scale
	//	max_value	not set for scale
	//	min_value	not set for scale
	scale_prop.set_max_alarm("1.0");
	scale_prop.set_min_alarm("0.0");
	//	max_warning	not set for scale
	//	min_warning	not set for scale
	//	delta_t	not set for scale
	//	delta_val	not set for scale
	
	scale->set_default_properties(scale_prop);
	//	Not Polled
	scale->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(scale);

	//	Attribute : frameRateMin
	frameRateMinAttrib	*frameratemin = new frameRateMinAttrib();
	Tango::UserDefaultAttrProp	frameratemin_prop;
	//	description	not set for frameRateMin
	//	label	not set for frameRateMin
	//	unit	not set for frameRateMin
	//	standard_unit	not set for frameRateMin
	//	display_unit	not set for frameRateMin
	//	format	not set for frameRateMin
	//	max_value	not set for frameRateMin
	//	min_value	not set for frameRateMin
	//	max_alarm	not set for frameRateMin
	//	min_alarm	not set for frameRateMin
	//	max_warning	not set for frameRateMin
	//	min_warning	not set for frameRateMin
	//	delta_t	not set for frameRateMin
	//	delta_val	not set for frameRateMin
	
	frameratemin->set_default_properties(frameratemin_prop);
	//	Not Polled
	frameratemin->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(frameratemin);

	//	Attribute : frameRateMax
	frameRateMaxAttrib	*frameratemax = new frameRateMaxAttrib();
	Tango::UserDefaultAttrProp	frameratemax_prop;
	//	description	not set for frameRateMax
	//	label	not set for frameRateMax
	//	unit	not set for frameRateMax
	//	standard_unit	not set for frameRateMax
	//	display_unit	not set for frameRateMax
	//	format	not set for frameRateMax
	//	max_value	not set for frameRateMax
	//	min_value	not set for frameRateMax
	//	max_alarm	not set for frameRateMax
	//	min_alarm	not set for frameRateMax
	//	max_warning	not set for frameRateMax
	//	min_warning	not set for frameRateMax
	//	delta_t	not set for frameRateMax
	//	delta_val	not set for frameRateMax
	
	frameratemax->set_default_properties(frameratemax_prop);
	//	Not Polled
	frameratemax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(frameratemax);

	//	Attribute : exposureMin
	exposureMinAttrib	*exposuremin = new exposureMinAttrib();
	Tango::UserDefaultAttrProp	exposuremin_prop;
	//	description	not set for exposureMin
	//	label	not set for exposureMin
	//	unit	not set for exposureMin
	//	standard_unit	not set for exposureMin
	//	display_unit	not set for exposureMin
	//	format	not set for exposureMin
	//	max_value	not set for exposureMin
	//	min_value	not set for exposureMin
	//	max_alarm	not set for exposureMin
	//	min_alarm	not set for exposureMin
	//	max_warning	not set for exposureMin
	//	min_warning	not set for exposureMin
	//	delta_t	not set for exposureMin
	//	delta_val	not set for exposureMin
	
	exposuremin->set_default_properties(exposuremin_prop);
	//	Not Polled
	exposuremin->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(exposuremin);

	//	Attribute : exposureMax
	exposureMaxAttrib	*exposuremax = new exposureMaxAttrib();
	Tango::UserDefaultAttrProp	exposuremax_prop;
	//	description	not set for exposureMax
	//	label	not set for exposureMax
	//	unit	not set for exposureMax
	//	standard_unit	not set for exposureMax
	//	display_unit	not set for exposureMax
	//	format	not set for exposureMax
	//	max_value	not set for exposureMax
	//	min_value	not set for exposureMax
	//	max_alarm	not set for exposureMax
	//	min_alarm	not set for exposureMax
	//	max_warning	not set for exposureMax
	//	min_warning	not set for exposureMax
	//	delta_t	not set for exposureMax
	//	delta_val	not set for exposureMax
	
	exposuremax->set_default_properties(exposuremax_prop);
	//	Not Polled
	exposuremax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(exposuremax);

	//	Attribute : brightnessMin
	brightnessMinAttrib	*brightnessmin = new brightnessMinAttrib();
	Tango::UserDefaultAttrProp	brightnessmin_prop;
	//	description	not set for brightnessMin
	//	label	not set for brightnessMin
	//	unit	not set for brightnessMin
	//	standard_unit	not set for brightnessMin
	//	display_unit	not set for brightnessMin
	//	format	not set for brightnessMin
	//	max_value	not set for brightnessMin
	//	min_value	not set for brightnessMin
	//	max_alarm	not set for brightnessMin
	//	min_alarm	not set for brightnessMin
	//	max_warning	not set for brightnessMin
	//	min_warning	not set for brightnessMin
	//	delta_t	not set for brightnessMin
	//	delta_val	not set for brightnessMin
	
	brightnessmin->set_default_properties(brightnessmin_prop);
	//	Not Polled
	brightnessmin->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(brightnessmin);

	//	Attribute : brightnessMax
	brightnessMaxAttrib	*brightnessmax = new brightnessMaxAttrib();
	Tango::UserDefaultAttrProp	brightnessmax_prop;
	//	description	not set for brightnessMax
	//	label	not set for brightnessMax
	//	unit	not set for brightnessMax
	//	standard_unit	not set for brightnessMax
	//	display_unit	not set for brightnessMax
	//	format	not set for brightnessMax
	//	max_value	not set for brightnessMax
	//	min_value	not set for brightnessMax
	//	max_alarm	not set for brightnessMax
	//	min_alarm	not set for brightnessMax
	//	max_warning	not set for brightnessMax
	//	min_warning	not set for brightnessMax
	//	delta_t	not set for brightnessMax
	//	delta_val	not set for brightnessMax
	
	brightnessmax->set_default_properties(brightnessmax_prop);
	//	Not Polled
	brightnessmax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(brightnessmax);

	//	Attribute : gammaMin
	gammaMinAttrib	*gammamin = new gammaMinAttrib();
	Tango::UserDefaultAttrProp	gammamin_prop;
	//	description	not set for gammaMin
	//	label	not set for gammaMin
	//	unit	not set for gammaMin
	//	standard_unit	not set for gammaMin
	//	display_unit	not set for gammaMin
	//	format	not set for gammaMin
	//	max_value	not set for gammaMin
	//	min_value	not set for gammaMin
	//	max_alarm	not set for gammaMin
	//	min_alarm	not set for gammaMin
	//	max_warning	not set for gammaMin
	//	min_warning	not set for gammaMin
	//	delta_t	not set for gammaMin
	//	delta_val	not set for gammaMin
	
	gammamin->set_default_properties(gammamin_prop);
	//	Not Polled
	gammamin->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gammamin);

	//	Attribute : gammaMax
	gammaMaxAttrib	*gammamax = new gammaMaxAttrib();
	Tango::UserDefaultAttrProp	gammamax_prop;
	//	description	not set for gammaMax
	//	label	not set for gammaMax
	//	unit	not set for gammaMax
	//	standard_unit	not set for gammaMax
	//	display_unit	not set for gammaMax
	//	format	not set for gammaMax
	//	max_value	not set for gammaMax
	//	min_value	not set for gammaMax
	//	max_alarm	not set for gammaMax
	//	min_alarm	not set for gammaMax
	//	max_warning	not set for gammaMax
	//	min_warning	not set for gammaMax
	//	delta_t	not set for gammaMax
	//	delta_val	not set for gammaMax
	
	gammamax->set_default_properties(gammamax_prop);
	//	Not Polled
	gammamax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gammamax);

	//	Attribute : gainMin
	gainMinAttrib	*gainmin = new gainMinAttrib();
	Tango::UserDefaultAttrProp	gainmin_prop;
	//	description	not set for gainMin
	//	label	not set for gainMin
	//	unit	not set for gainMin
	//	standard_unit	not set for gainMin
	//	display_unit	not set for gainMin
	//	format	not set for gainMin
	//	max_value	not set for gainMin
	//	min_value	not set for gainMin
	//	max_alarm	not set for gainMin
	//	min_alarm	not set for gainMin
	//	max_warning	not set for gainMin
	//	min_warning	not set for gainMin
	//	delta_t	not set for gainMin
	//	delta_val	not set for gainMin
	
	gainmin->set_default_properties(gainmin_prop);
	//	Not Polled
	gainmin->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gainmin);

	//	Attribute : gainMax
	gainMaxAttrib	*gainmax = new gainMaxAttrib();
	Tango::UserDefaultAttrProp	gainmax_prop;
	//	description	not set for gainMax
	//	label	not set for gainMax
	//	unit	not set for gainMax
	//	standard_unit	not set for gainMax
	//	display_unit	not set for gainMax
	//	format	not set for gainMax
	//	max_value	not set for gainMax
	//	min_value	not set for gainMax
	//	max_alarm	not set for gainMax
	//	min_alarm	not set for gainMax
	//	max_warning	not set for gainMax
	//	min_warning	not set for gainMax
	//	delta_t	not set for gainMax
	//	delta_val	not set for gainMax
	
	gainmax->set_default_properties(gainmax_prop);
	//	Not Polled
	gainmax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(gainmax);

	//	Attribute : shutterMin
	shutterMinAttrib	*shuttermin = new shutterMinAttrib();
	Tango::UserDefaultAttrProp	shuttermin_prop;
	//	description	not set for shutterMin
	//	label	not set for shutterMin
	//	unit	not set for shutterMin
	//	standard_unit	not set for shutterMin
	//	display_unit	not set for shutterMin
	//	format	not set for shutterMin
	//	max_value	not set for shutterMin
	//	min_value	not set for shutterMin
	//	max_alarm	not set for shutterMin
	//	min_alarm	not set for shutterMin
	//	max_warning	not set for shutterMin
	//	min_warning	not set for shutterMin
	//	delta_t	not set for shutterMin
	//	delta_val	not set for shutterMin
	
	shuttermin->set_default_properties(shuttermin_prop);
	//	Not Polled
	shuttermin->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(shuttermin);

	//	Attribute : shutterMax
	shutterMaxAttrib	*shuttermax = new shutterMaxAttrib();
	Tango::UserDefaultAttrProp	shuttermax_prop;
	//	description	not set for shutterMax
	//	label	not set for shutterMax
	//	unit	not set for shutterMax
	//	standard_unit	not set for shutterMax
	//	display_unit	not set for shutterMax
	//	format	not set for shutterMax
	//	max_value	not set for shutterMax
	//	min_value	not set for shutterMax
	//	max_alarm	not set for shutterMax
	//	min_alarm	not set for shutterMax
	//	max_warning	not set for shutterMax
	//	min_warning	not set for shutterMax
	//	delta_t	not set for shutterMax
	//	delta_val	not set for shutterMax
	
	shuttermax->set_default_properties(shuttermax_prop);
	//	Not Polled
	shuttermax->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(shuttermax);

	//	Attribute : imageEncodedJpeg
	imageEncodedJpegAttrib	*imageencodedjpeg = new imageEncodedJpegAttrib();
	Tango::UserDefaultAttrProp	imageencodedjpeg_prop;
	//	description	not set for imageEncodedJpeg
	//	label	not set for imageEncodedJpeg
	//	unit	not set for imageEncodedJpeg
	//	standard_unit	not set for imageEncodedJpeg
	//	display_unit	not set for imageEncodedJpeg
	//	format	not set for imageEncodedJpeg
	//	max_value	not set for imageEncodedJpeg
	//	min_value	not set for imageEncodedJpeg
	//	max_alarm	not set for imageEncodedJpeg
	//	min_alarm	not set for imageEncodedJpeg
	//	max_warning	not set for imageEncodedJpeg
	//	min_warning	not set for imageEncodedJpeg
	//	delta_t	not set for imageEncodedJpeg
	//	delta_val	not set for imageEncodedJpeg
	
	imageencodedjpeg->set_default_properties(imageencodedjpeg_prop);
	//	Not Polled
	imageencodedjpeg->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	imageencodedjpeg->set_data_ready_event(true);
	att_list.push_back(imageencodedjpeg);

	//	Attribute : fullImage
	fullImageAttrib	*fullimage = new fullImageAttrib();
	Tango::UserDefaultAttrProp	fullimage_prop;
	//	description	not set for fullImage
	//	label	not set for fullImage
	//	unit	not set for fullImage
	//	standard_unit	not set for fullImage
	//	display_unit	not set for fullImage
	//	format	not set for fullImage
	//	max_value	not set for fullImage
	//	min_value	not set for fullImage
	//	max_alarm	not set for fullImage
	//	min_alarm	not set for fullImage
	//	max_warning	not set for fullImage
	//	min_warning	not set for fullImage
	//	delta_t	not set for fullImage
	//	delta_val	not set for fullImage
	
	fullimage->set_default_properties(fullimage_prop);
	//	Not Polled
	fullimage->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(fullimage);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::pipe_factory_before
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::command_factory()
{
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::command_factory_before


	//	Command play
	playClass	*pplayCmd =
		new playClass("play",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pplayCmd);

	//	Command pause
	pauseClass	*ppauseCmd =
		new pauseClass("pause",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(ppauseCmd);

	//	Command setExposure
	setExposureClass	*psetExposureCmd =
		new setExposureClass("setExposure",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(psetExposureCmd);

	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		CcdCameraChameleonClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		CcdCameraChameleonClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void CcdCameraChameleonClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		CcdCameraChameleon *dev = static_cast<CcdCameraChameleon *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(CcdCameraChameleonClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleonClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *CcdCameraChameleonClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(CcdCameraChameleonClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleonClass::Additional Methods
} //	namespace
