/*----- PROTECTED REGION ID(CcdCameraChameleonStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        CcdCameraChameleonStateMachine.cpp
//
// description : State machine file for the CcdCameraChameleon class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <CcdCameraChameleon.h>

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::CcdCameraChameleonStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace CcdCameraChameleon_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_frameRate_allowed()
 *	Description : Execution allowed for frameRate attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_frameRate_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for frameRate attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::frameRateStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::frameRateStateAllowed_WRITE

	//	Not any excluded states for frameRate attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::frameRateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::frameRateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_brightness_allowed()
 *	Description : Execution allowed for brightness attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_brightness_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for brightness attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::brightnessStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::brightnessStateAllowed_WRITE

	//	Not any excluded states for brightness attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::brightnessStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::brightnessStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_exposure_allowed()
 *	Description : Execution allowed for exposure attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_exposure_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exposure attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureStateAllowed_WRITE

	//	Not any excluded states for exposure attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_gamma_allowed()
 *	Description : Execution allowed for gamma attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_gamma_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for gamma attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gammaStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gammaStateAllowed_WRITE

	//	Not any excluded states for gamma attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gammaStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gammaStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_shutter_allowed()
 *	Description : Execution allowed for shutter attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_shutter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for shutter attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::shutterStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::shutterStateAllowed_WRITE

	//	Not any excluded states for shutter attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::shutterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::shutterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_gain_allowed()
 *	Description : Execution allowed for gain attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_gain_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for gain attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gainStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gainStateAllowed_WRITE

	//	Not any excluded states for gain attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gainStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gainStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_x_allowed()
 *	Description : Execution allowed for x attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_x_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for x attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::xStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::xStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_y_allowed()
 *	Description : Execution allowed for y attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_y_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for y attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::yStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::yStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_a_allowed()
 *	Description : Execution allowed for a attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_a_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for a attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::aStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::aStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_b_allowed()
 *	Description : Execution allowed for b attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_b_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::bStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::bStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_frameRateAuto_allowed()
 *	Description : Execution allowed for frameRateAuto attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_frameRateAuto_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for frameRateAuto attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::frameRateAutoStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::frameRateAutoStateAllowed_WRITE

	//	Not any excluded states for frameRateAuto attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::frameRateAutoStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::frameRateAutoStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_frameRateOnOff_allowed()
 *	Description : Execution allowed for frameRateOnOff attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_frameRateOnOff_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for frameRateOnOff attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::frameRateOnOffStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::frameRateOnOffStateAllowed_WRITE

	//	Not any excluded states for frameRateOnOff attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::frameRateOnOffStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::frameRateOnOffStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_exposureAuto_allowed()
 *	Description : Execution allowed for exposureAuto attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_exposureAuto_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exposureAuto attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureAutoStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureAutoStateAllowed_WRITE

	//	Not any excluded states for exposureAuto attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureAutoStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureAutoStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_exposureOnOff_allowed()
 *	Description : Execution allowed for exposureOnOff attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_exposureOnOff_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exposureOnOff attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureOnOffStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureOnOffStateAllowed_WRITE

	//	Not any excluded states for exposureOnOff attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureOnOffStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureOnOffStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_exposureOnePush_allowed()
 *	Description : Execution allowed for exposureOnePush attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_exposureOnePush_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for exposureOnePush attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureOnePushStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureOnePushStateAllowed_WRITE

	//	Not any excluded states for exposureOnePush attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::exposureOnePushStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::exposureOnePushStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_gammaOnOff_allowed()
 *	Description : Execution allowed for gammaOnOff attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_gammaOnOff_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for gammaOnOff attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gammaOnOffStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gammaOnOffStateAllowed_WRITE

	//	Not any excluded states for gammaOnOff attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gammaOnOffStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gammaOnOffStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_gainAuto_allowed()
 *	Description : Execution allowed for gainAuto attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_gainAuto_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for gainAuto attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gainAutoStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gainAutoStateAllowed_WRITE

	//	Not any excluded states for gainAuto attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gainAutoStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gainAutoStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_gainOnePush_allowed()
 *	Description : Execution allowed for gainOnePush attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_gainOnePush_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for gainOnePush attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gainOnePushStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gainOnePushStateAllowed_WRITE

	//	Not any excluded states for gainOnePush attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::gainOnePushStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::gainOnePushStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_shutterAuto_allowed()
 *	Description : Execution allowed for shutterAuto attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_shutterAuto_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for shutterAuto attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::shutterAutoStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::shutterAutoStateAllowed_WRITE

	//	Not any excluded states for shutterAuto attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::shutterAutoStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::shutterAutoStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_shutterOnePush_allowed()
 *	Description : Execution allowed for shutterOnePush attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_shutterOnePush_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for shutterOnePush attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::shutterOnePushStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::shutterOnePushStateAllowed_WRITE

	//	Not any excluded states for shutterOnePush attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::shutterOnePushStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::shutterOnePushStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_temperature_allowed()
 *	Description : Execution allowed for temperature attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_temperature_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for temperature attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::temperatureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::temperatureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_imageWidth_allowed()
 *	Description : Execution allowed for imageWidth attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_imageWidth_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for imageWidth attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::imageWidthStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::imageWidthStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_imageHeight_allowed()
 *	Description : Execution allowed for imageHeight attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_imageHeight_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for imageHeight attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::imageHeightStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::imageHeightStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_quality_allowed()
 *	Description : Execution allowed for quality attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_quality_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for quality attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::qualityStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::qualityStateAllowed_WRITE

	//	Not any excluded states for quality attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::qualityStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::qualityStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_phi_allowed()
 *	Description : Execution allowed for phi attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_phi_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for phi attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::phiStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::phiStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_scale_allowed()
 *	Description : Execution allowed for scale attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_scale_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for scale attribute in Write access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::scaleStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::scaleStateAllowed_WRITE

	//	Not any excluded states for scale attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::scaleStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::scaleStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_imageEncodedJpeg_allowed()
 *	Description : Execution allowed for imageEncodedJpeg attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_imageEncodedJpeg_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for imageEncodedJpeg attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::imageEncodedJpegStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::imageEncodedJpegStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_fullImage_allowed()
 *	Description : Execution allowed for fullImage attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_fullImage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for fullImage attribute in read access.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::fullImageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::fullImageStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_play_allowed()
 *	Description : Execution allowed for play attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_play_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for play command.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::playStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::playStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : CcdCameraChameleon::is_pause_allowed()
 *	Description : Execution allowed for pause attribute
 */
//--------------------------------------------------------
bool CcdCameraChameleon::is_pause_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for pause command.
	/*----- PROTECTED REGION ID(CcdCameraChameleon::pauseStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::pauseStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(CcdCameraChameleon::CcdCameraChameleonStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::CcdCameraChameleonStateAllowed.AdditionalMethods

}	//	End of namespace
