/*----- PROTECTED REGION ID(CcdCameraChameleon.h) ENABLED START -----*/
//=============================================================================
//
// file :        CcdCameraChameleon.h
//
// description : Include file for the CcdCameraChameleon class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef CcdCameraChameleon_H
#define CcdCameraChameleon_H

#include <tango.h>
#include "camerachameleon.h"

class CameraChameleon;

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon.h

/**
 *  CcdCameraChameleon class description:
 *    
 */

namespace CcdCameraChameleon_ns
{
/*----- PROTECTED REGION ID(CcdCameraChameleon::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::Additional Class Declarations

class CcdCameraChameleon : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(CcdCameraChameleon::Data Members) ENABLED START -----*/

//	Add your own data members
	CameraChameleon* camera;

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::Data Members

//	Device property data members
public:
	//	serialNumber:	
	vector<Tango::DevLong>	serialNumber;

//	Attribute data members
public:
	Tango::DevDouble	*attr_frameRate_read;
	Tango::DevDouble	*attr_brightness_read;
	Tango::DevDouble	*attr_exposure_read;
	Tango::DevDouble	*attr_gamma_read;
	Tango::DevDouble	*attr_shutter_read;
	Tango::DevDouble	*attr_gain_read;
	Tango::DevDouble	*attr_x_read;
	Tango::DevDouble	*attr_y_read;
	Tango::DevDouble	*attr_a_read;
	Tango::DevDouble	*attr_b_read;
	Tango::DevBoolean	*attr_frameRateAuto_read;
	Tango::DevBoolean	*attr_frameRateOnOff_read;
	Tango::DevBoolean	*attr_exposureAuto_read;
	Tango::DevBoolean	*attr_exposureOnOff_read;
	Tango::DevBoolean	*attr_exposureOnePush_read;
	Tango::DevBoolean	*attr_gammaOnOff_read;
	Tango::DevBoolean	*attr_gainAuto_read;
	Tango::DevBoolean	*attr_gainOnePush_read;
	Tango::DevBoolean	*attr_shutterAuto_read;
	Tango::DevBoolean	*attr_shutterOnePush_read;
	Tango::DevDouble	*attr_temperature_read;
	Tango::DevLong	*attr_imageWidth_read;
	Tango::DevLong	*attr_imageHeight_read;
	Tango::DevLong	*attr_quality_read;
	Tango::DevDouble	*attr_phi_read;
	Tango::DevDouble	*attr_scale_read;
	Tango::DevDouble	*attr_frameRateMin_read;
	Tango::DevDouble	*attr_frameRateMax_read;
	Tango::DevDouble	*attr_exposureMin_read;
	Tango::DevDouble	*attr_exposureMax_read;
	Tango::DevDouble	*attr_brightnessMin_read;
	Tango::DevDouble	*attr_brightnessMax_read;
	Tango::DevDouble	*attr_gammaMin_read;
	Tango::DevDouble	*attr_gammaMax_read;
	Tango::DevDouble	*attr_gainMin_read;
	Tango::DevDouble	*attr_gainMax_read;
	Tango::DevDouble	*attr_shutterMin_read;
	Tango::DevDouble	*attr_shutterMax_read;
	Tango::DevUChar	*attr_imageEncodedJpeg_read;
	Tango::DevUChar	*attr_fullImage_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	CcdCameraChameleon(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	CcdCameraChameleon(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	CcdCameraChameleon(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~CcdCameraChameleon() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : CcdCameraChameleon::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : CcdCameraChameleon::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute frameRate related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_frameRate(Tango::Attribute &attr);
	virtual void write_frameRate(Tango::WAttribute &attr);
	virtual bool is_frameRate_allowed(Tango::AttReqType type);
/**
 *	Attribute brightness related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_brightness(Tango::Attribute &attr);
	virtual void write_brightness(Tango::WAttribute &attr);
	virtual bool is_brightness_allowed(Tango::AttReqType type);
/**
 *	Attribute exposure related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_exposure(Tango::Attribute &attr);
	virtual void write_exposure(Tango::WAttribute &attr);
	virtual bool is_exposure_allowed(Tango::AttReqType type);
/**
 *	Attribute gamma related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_gamma(Tango::Attribute &attr);
	virtual void write_gamma(Tango::WAttribute &attr);
	virtual bool is_gamma_allowed(Tango::AttReqType type);
/**
 *	Attribute shutter related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_shutter(Tango::Attribute &attr);
	virtual void write_shutter(Tango::WAttribute &attr);
	virtual bool is_shutter_allowed(Tango::AttReqType type);
/**
 *	Attribute gain related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_gain(Tango::Attribute &attr);
	virtual void write_gain(Tango::WAttribute &attr);
	virtual bool is_gain_allowed(Tango::AttReqType type);
/**
 *	Attribute x related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_x(Tango::Attribute &attr);
	virtual bool is_x_allowed(Tango::AttReqType type);
/**
 *	Attribute y related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_y(Tango::Attribute &attr);
	virtual bool is_y_allowed(Tango::AttReqType type);
/**
 *	Attribute a related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_a(Tango::Attribute &attr);
	virtual bool is_a_allowed(Tango::AttReqType type);
/**
 *	Attribute b related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_b(Tango::Attribute &attr);
	virtual bool is_b_allowed(Tango::AttReqType type);
/**
 *	Attribute frameRateAuto related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_frameRateAuto(Tango::Attribute &attr);
	virtual void write_frameRateAuto(Tango::WAttribute &attr);
	virtual bool is_frameRateAuto_allowed(Tango::AttReqType type);
/**
 *	Attribute frameRateOnOff related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_frameRateOnOff(Tango::Attribute &attr);
	virtual void write_frameRateOnOff(Tango::WAttribute &attr);
	virtual bool is_frameRateOnOff_allowed(Tango::AttReqType type);
/**
 *	Attribute exposureAuto related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_exposureAuto(Tango::Attribute &attr);
	virtual void write_exposureAuto(Tango::WAttribute &attr);
	virtual bool is_exposureAuto_allowed(Tango::AttReqType type);
/**
 *	Attribute exposureOnOff related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_exposureOnOff(Tango::Attribute &attr);
	virtual void write_exposureOnOff(Tango::WAttribute &attr);
	virtual bool is_exposureOnOff_allowed(Tango::AttReqType type);
/**
 *	Attribute exposureOnePush related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_exposureOnePush(Tango::Attribute &attr);
	virtual void write_exposureOnePush(Tango::WAttribute &attr);
	virtual bool is_exposureOnePush_allowed(Tango::AttReqType type);
/**
 *	Attribute gammaOnOff related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_gammaOnOff(Tango::Attribute &attr);
	virtual void write_gammaOnOff(Tango::WAttribute &attr);
	virtual bool is_gammaOnOff_allowed(Tango::AttReqType type);
/**
 *	Attribute gainAuto related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_gainAuto(Tango::Attribute &attr);
	virtual void write_gainAuto(Tango::WAttribute &attr);
	virtual bool is_gainAuto_allowed(Tango::AttReqType type);
/**
 *	Attribute gainOnePush related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_gainOnePush(Tango::Attribute &attr);
	virtual void write_gainOnePush(Tango::WAttribute &attr);
	virtual bool is_gainOnePush_allowed(Tango::AttReqType type);
/**
 *	Attribute shutterAuto related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_shutterAuto(Tango::Attribute &attr);
	virtual void write_shutterAuto(Tango::WAttribute &attr);
	virtual bool is_shutterAuto_allowed(Tango::AttReqType type);
/**
 *	Attribute shutterOnePush related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_shutterOnePush(Tango::Attribute &attr);
	virtual void write_shutterOnePush(Tango::WAttribute &attr);
	virtual bool is_shutterOnePush_allowed(Tango::AttReqType type);
/**
 *	Attribute temperature related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_temperature(Tango::Attribute &attr);
	virtual bool is_temperature_allowed(Tango::AttReqType type);
/**
 *	Attribute imageWidth related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_imageWidth(Tango::Attribute &attr);
	virtual bool is_imageWidth_allowed(Tango::AttReqType type);
/**
 *	Attribute imageHeight related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_imageHeight(Tango::Attribute &attr);
	virtual bool is_imageHeight_allowed(Tango::AttReqType type);
/**
 *	Attribute quality related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_quality(Tango::Attribute &attr);
	virtual void write_quality(Tango::WAttribute &attr);
	virtual bool is_quality_allowed(Tango::AttReqType type);
/**
 *	Attribute phi related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_phi(Tango::Attribute &attr);
	virtual bool is_phi_allowed(Tango::AttReqType type);
/**
 *	Attribute scale related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_scale(Tango::Attribute &attr);
	virtual void write_scale(Tango::WAttribute &attr);
	virtual bool is_scale_allowed(Tango::AttReqType type);
/**
 *	Attribute frameRateMin related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_frameRateMin(Tango::Attribute &attr);
	virtual bool is_frameRateMin_allowed(Tango::AttReqType type);
/**
 *	Attribute frameRateMax related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_frameRateMax(Tango::Attribute &attr);
	virtual bool is_frameRateMax_allowed(Tango::AttReqType type);
/**
 *	Attribute exposureMin related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_exposureMin(Tango::Attribute &attr);
	virtual bool is_exposureMin_allowed(Tango::AttReqType type);
/**
 *	Attribute exposureMax related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_exposureMax(Tango::Attribute &attr);
	virtual bool is_exposureMax_allowed(Tango::AttReqType type);
/**
 *	Attribute brightnessMin related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_brightnessMin(Tango::Attribute &attr);
	virtual bool is_brightnessMin_allowed(Tango::AttReqType type);
/**
 *	Attribute brightnessMax related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_brightnessMax(Tango::Attribute &attr);
	virtual bool is_brightnessMax_allowed(Tango::AttReqType type);
/**
 *	Attribute gammaMin related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_gammaMin(Tango::Attribute &attr);
	virtual bool is_gammaMin_allowed(Tango::AttReqType type);
/**
 *	Attribute gammaMax related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_gammaMax(Tango::Attribute &attr);
	virtual bool is_gammaMax_allowed(Tango::AttReqType type);
/**
 *	Attribute gainMin related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_gainMin(Tango::Attribute &attr);
	virtual bool is_gainMin_allowed(Tango::AttReqType type);
/**
 *	Attribute gainMax related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_gainMax(Tango::Attribute &attr);
	virtual bool is_gainMax_allowed(Tango::AttReqType type);
/**
 *	Attribute shutterMin related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_shutterMin(Tango::Attribute &attr);
	virtual bool is_shutterMin_allowed(Tango::AttReqType type);
/**
 *	Attribute shutterMax related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_shutterMax(Tango::Attribute &attr);
	virtual bool is_shutterMax_allowed(Tango::AttReqType type);
/**
 *	Attribute imageEncodedJpeg related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Spectrum max = 1228800
 */
	virtual void read_imageEncodedJpeg(Tango::Attribute &attr);
	virtual bool is_imageEncodedJpeg_allowed(Tango::AttReqType type);
/**
 *	Attribute fullImage related methods
 *	Description: 
 *
 *	Data type:	Tango::DevUChar
 *	Attr type:	Image max = 1280 x 960
 */
	virtual void read_fullImage(Tango::Attribute &attr);
	virtual bool is_fullImage_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : CcdCameraChameleon::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command play related method
	 *	Description: 
	 *
	 */
	virtual void play();
	virtual bool is_play_allowed(const CORBA::Any &any);
	/**
	 *	Command pause related method
	 *	Description: 
	 *
	 */
	virtual void pause();
	virtual bool is_pause_allowed(const CORBA::Any &any);
	/**
	 *	Command setExposure related method
	 *	Description: 
	 *
	 */
	virtual void set_exposure();
	virtual bool is_setExposure_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : CcdCameraChameleon::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(CcdCameraChameleon::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::Additional Method prototypes
};

/*----- PROTECTED REGION ID(CcdCameraChameleon::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	CcdCameraChameleon::Additional Classes Definitions

}	//	End of namespace

#endif   //	CcdCameraChameleon_H
